language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: "devoxx"
jdk:
  - oraclejdk8
script:
  - mvn clean package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
